name: Pipeline

on: [push]
env:
  APPLICATION_NAME: app2
jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python environment
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
        architecture: x64
    - name: Install requirements
      run: pip install --requirement requirements.txt
    - name: Lint code
      run: |
        flake8 --ignore=E501,E231,R1732,W1514 *.py
        pylint --disable=C0301 --disable=C0326 *.py
    - name: Run unit tests
      run: |
        python -m unittest --verbose --failfast
